// <auto-generated />
using ExtremePC.FileUpload.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExtremePC.FileUpload.Database.Migrations
{
    [DbContext(typeof(FileUploadDBContext))]
    [Migration("20190211012941_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExtremePC.FileUpload.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new { ColorId = 1, Name = "grijs" },
                        new { ColorId = 2, Name = "groen" },
                        new { ColorId = 3, Name = "wit" },
                        new { ColorId = 4, Name = "zwart" },
                        new { ColorId = 5, Name = "bruin" },
                        new { ColorId = 6, Name = "beige" },
                        new { ColorId = 7, Name = "rood" },
                        new { ColorId = 8, Name = "blauw" }
                    );
                });

            modelBuilder.Entity("ExtremePC.FileUpload.Models.ColorCode", b =>
                {
                    b.Property<int>("ColorCodeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ColorCodeId");

                    b.ToTable("ColorCodes");

                    b.HasData(
                        new { ColorCodeId = 1, Name = "broek" },
                        new { ColorCodeId = 2, Name = "Kniebroek Jorge" },
                        new { ColorCodeId = 3, Name = "Jeans" },
                        new { ColorCodeId = 4, Name = "Jeans Willy" },
                        new { ColorCodeId = 5, Name = "Kniebroek Maria" },
                        new { ColorCodeId = 6, Name = "Top Wilma" },
                        new { ColorCodeId = 7, Name = "Top Annie" },
                        new { ColorCodeId = 8, Name = "Top Bill" },
                        new { ColorCodeId = 9, Name = "Steve Irwin" },
                        new { ColorCodeId = 10, Name = "Jeans Willy Boys" },
                        new { ColorCodeId = 11, Name = "Short Billy & Bobble" },
                        new { ColorCodeId = 12, Name = "jacket" },
                        new { ColorCodeId = 13, Name = "test" }
                    );
                });

            modelBuilder.Entity("ExtremePC.FileUpload.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtikelCode");

                    b.Property<int>("ColorCodeId");

                    b.Property<int>("ColorId");

                    b.Property<int>("DeliveredInMax");

                    b.Property<int>("DeliveredInMin");

                    b.Property<string>("Description");

                    b.Property<decimal>("DiscountPrice");

                    b.Property<string>("Key");

                    b.Property<decimal>("Price");

                    b.Property<string>("Q1");

                    b.Property<int>("Size");

                    b.HasKey("ProductId");

                    b.HasIndex("ColorCodeId");

                    b.HasIndex("ColorId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ExtremePC.FileUpload.Models.Product", b =>
                {
                    b.HasOne("ExtremePC.FileUpload.Models.ColorCode", "ColorCode")
                        .WithMany("Products")
                        .HasForeignKey("ColorCodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ExtremePC.FileUpload.Models.Color", "Color")
                        .WithMany("Products")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
